ansible_user: vagrant
ansible_password: vagrant
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
ansible_winrm_port: 5985
ansible_winrm_read_timeout_sec: 120
ansible_winrm_operation_timeout_sec: 90
ansible_become: false

domain_admin_user: Administrator
domain_admin_password: "NovaTech_Admin2024!"
safe_mode_password: "DragonRx2024!"
