[docker_linux]
web01    ansible_host=192.168.10.100  ansible_connection=docker  ansible_docker_extra_args="-u root"  ansible_container=dragonrx_web01
kali     ansible_host=10.0.0.5       ansible_connection=docker  ansible_container=dragonrx_kali

[windows]
dc01     ansible_host=192.168.10.10
fs01     ansible_host=192.168.10.20
ws01     ansible_host=192.168.10.50

[all:vars]
domain_name=novatech.local
domain_netbios=NOVATECH
domain_controller_ip=192.168.10.10
